language: python
sudo: false

install:
  - pip install tox codecov

script:
  - tox -c tox.ini -e $TOX_ENV

after_script:
  - codecov

matrix:
  fast_finish: true
  include:
    - python: 3.5
      env: TOX_ENV=py35-tests
    - python: 3.6
      env: TOX_ENV=py36-tests
    - python: 3.6
      env: TOX_ENV=flake8
    - python: 3.6
      env: TOX_ENV=check-manifest
