language: python
sudo: false

install:
  - pip install tox codecov

before_script:
  - git remote set-branches --add origin master
  - git fetch origin master

script:
  - tox -c tox.ini -e $TOX_ENV

after_script:
  - codecov

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOX_ENV=flake8
    - python: 3.6
      env: TOX_ENV=check-manifest
    - python: 3.6
      env: TOX_ENV=check-newsfragment
    - python: pypy
      env: TOX_ENV=pypy-tests
    - python: 2.7
      env: TOX_ENV=py27-tests
    - python: 3.4
      env: TOX_ENV=py34-tests
    - python: 3.5
      env: TOX_ENV=py35-tests
    - python: 3.6
      env: TOX_ENV=py36-tests
